#!/bin/csh
# lil script to pipe anything ending in .eml in the directory to mutt
# (i.e., to send it)
# 
# NB: the script has a 2-second cooling off period to cancel if you want

echo "files to send:"
echo
ls -1 *.eml  | awk '{print NR,$0}'
echo
sleep 2

setenv odir "sent/`date +%yy%mm%dd_%Hh%Mm%Ss`"
#echo $odir
mkdir -pv $odir

foreach thing (*.eml)
    echo "sending" $thing "..."
    cat /dev/null | mutt -H $thing
    echo "... $thing done"
    mv -f $thing $odir
end
