#!/bin/csh
# (c) chris.wiggins@gmail.com
# permission intro script 2013
#
 
ii $1 $2 > /dev/null

# COPY FROM II
setenv dfile nfile.asc  # datafile

setenv str1 `grep -i ';'$1';' $dfile|tail -1 | tr '[A-Z]' '[a-z]'`
setenv str2 `grep -i ';'$2';' $dfile|tail -1 | tr '[A-Z]' '[a-z]'`
setenv f1 `echo $str1 | awk -F\; '{print $1}'`
setenv f2 `echo $str2 | awk -F\; '{print $1}'`
setenv l1 `echo $str1 | awk -F\; '{print $2}'`
setenv l2 `echo $str2 | awk -F\; '{print $2}'`
setenv e1 `echo $str1 | awk -F\; '{print $3}'`
setenv e2 `echo $str2 | awk -F\; '{print $3}'`
# END COPY
#
setenv ofile ${l1}_${l2}-pts.eml

cat >! $ofile << EOF
From: chris wiggins
User-Agent: SNDMSG
Time: `date` (NYC)
To: $e2
Subject: Permission request to intro $f1 $l1 <-> $f2 $l2

@${f2}:

I'd like your permission to intro you to $f1 $l1.

The proposed email I'd send is below. Please
let me know if this is ok with you. If you'd
like to make edits or would prefer I not
for any reason, no problem at all, happy to.
Just let me know.

Best,

Chris

======

EOF

grep -v -e '^Time: ' < ${l1}_{$l2}.eml >> $ofile

mkdir proposed

mv -f ${l1}_{$l2}.eml proposed

more $ofile
