#!/bin/csh
# script to ask for permission to intro people
# based on "orly" ii script 2011-2015
# modified mar 2015 to make modular i.e., pti calls ii

# call ii to make intro email
ii $1 $2
# recover variables
source /tmp/orly-vars.sh
# define the output file
setenv ofile ${l1}_${l2}-pts.eml

# preamble begin
cat >! $ofile << EOF
bcc: chris+cwbook@hackNY.org
User-Agent: SNDMSG
Time: `date` (NYC)
To: $e2
Subject: Permission request to intro $f1 $n1 <-> $f2 $n2

@${f2}:

I'd like your permission to intro you to $f1 $n1.

The proposed email I'd send is below. Please
let me know if this is ok with you. If you'd
like to make edits or would prefer I not
for any reason, no problem at all, happy to.
Just let me know.

Best,

Chris

======
EOF
# preamble end

# wrap it up
mkdir proposed
cat ${l1}_{$l2}.eml >> $ofile
mv -f ${l1}_{$l2}.eml proposed
more $ofile
